apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: familie-ef-navno
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 8080
  liveness:
    path: /familie/alene-med-barn/status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /familie/alene-med-barn/status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: false
  ingresses:
    "https://familie-ef-navno.adeo.no"
  accessPolicy:
    outbound:
      rules:
        - application: familie-ef-navno
      external:
        - host: appres.nav.no
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: APPRES_CMS_URL
      value: https://appres.nav.no

  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
