apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: familie-ef-soknad
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: navikt/familie-ef-soknad:{{version}}
  team: teamfamilie
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  port: 8080
  liveness:
    path: /status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: false
  ingresses:
    - https://familie-gcp.nav.no/familie/alene-med-barn/soknad/navno
  accessPolicy:
    outbound:
      rules:
        - application: familie-ef-soknad-api
      external:
        - host: appres.nav.no
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: APPRES_CMS_URL
      value: https://appres.nav.no

  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
