apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: familie-ef-navno
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
  port: 8080
  liveness:
    path: /status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /status
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: false
  ingresses:
    - https://familie-ef-navno.ekstern.dev.nav.no
  env:
    - name: APP_VERSION
      value: '{{version}}'
    - name: APPRES_CMS_URL
      value: https://appres-q0.nav.no

  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 128Mi
