name: Build, push, and deploy app to prod

on:
  push:
    branches:
      - 'main'

env:
  IMAGE: ghcr.io/navikt/familie-ef-navno:${{ github.sha }}

jobs:
  build:
    name: Install dependencies and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Yarn install
        run: yarn --prefer-ofline --frozen-lockfile
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build . -t ${IMAGE}
          docker login ghcr.io -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}
  deploy:
    name: Deploy to NAIS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .build/gcp-nais-dev.yaml
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .build/gcp-nais-prod.yaml