name: Build, push, and deploy app to dev

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Install dependencies and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - name: Yarn install
        run: yarn --prefer-offline --frozen-lockfile
      - name: Push docker image to GAR and sign image
        uses: nais/docker-build-push@791ebb6f74b82849c742a9bc9c97abe44c6c111f # ratchet:nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamfamilie
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
  deploy:
    name: Deploy to dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
      - uses: nais/deploy/actions/deploy@655191e618af58744d594ab4226aeac78dc739ec # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .build/app-dev.yaml
          IMAGE: ${{ needs.build.outputs.image }}
