name: Build app

on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Yarn install
        run: yarn --prefer-offline --frozen-lockfile
